### ISSUE TITLE
Offer human readable output by default

### ISSUE THREAD

**Issue by fyrak1s** [orf/dirscan#4]
It is nice that we can scan directories and get everything in json form.

However if I want to use dirscan as a system tool on a daily basis, I would like to get readable output instantly.

`dirscan scan <PATH>` should therefore by default, offer it's content in a human readable and consumable form, unless for example `--format=json` is defined.

I think that would make it more accessible and universal:)

**Comment by orf** [comment]
Hey!
I appreciate you opening the issue, but I built dirscan as a tool to scan volumes that are too large to be analyzed in a human readable form. The point of the tool is to stream a non-consistent snapshot of a given volume to a JSON or CSV file for later analysis (ideally an automated analysis).

If you're planning to use this on consumer-sized disks, then the excellent dua might be what you're looking for? https://github.com/Byron/dua-cli

**Comment by fyrak1s** [comment]
> If you're planning to use this on consumer-sized disks, then the excellent dua might be what you're looking for? https://github.com/Byron/dua-cli

Uhh yes, that's a good one! Thank you so much.
