### ISSUE TITLE
[Feature Request] Add support for listing file sizes

### ISSUE THREAD

**Issue by fyrak1s** [orf/dirscan#7]
We often want to know which directories clog up disk space.

But looking closer it might be interesting which files specifically require a lot of space, or if it is a homogeneous collection of smaller files.

EDIT: Btw sorry for creating so many bug reports :joy:

**Comment by orf** [comment]
No problem with the large number of issues! Thank you for suggesting improvements <3.

There's more I could add around the distribution of stats within a directory, but for now I've added the "largest file size" statistic for each directory 👍
